name: pbj
channels:
  - conda-forge
  - defaults
  - eumetsat
dependencies:
  - python=3.9
  - fftw3
  - jupyter
  - llvmlite
  - matplotlib
  - numpy
  - numba
  - ocl-icd
  - openblas=0.3.9
  - pdb2pqr
  - pip
  - plotly
  - pocl=1.7
  - pybind11
  - pyopencl
  - scipy
  - tbb
  - pip:
    - meshio
    - gmsh
    - trimesh
    - pytest
    - "git+https://github.com/bempp/bempp-cl.git"
    - "git+https://github.com/exafmm/exafmm-t.git"
    - "git+https://github.com/bem4solvation/pbj.git"
