name: pbj
channels:
  - conda-forge
  - defaults
  - eumetsat
dependencies:
  - fftw3
  - git
  - ipython
  - jupyter
  - llvmlite
  - llvmlite
  - mako
  - notebook
  - numba
  - numpy
  - ocl-icd
  - openblas=0.3.9
  - pdb2pqr
  - pip
  - plotly
  - pocl
  - pybind11
  - pyopencl
  - python
  - scipy
  - tbb
  - pip:
    - meshio
    - trimesh
    - "git+https://github.com/bempp/bempp-cl.git"
    - "git+https://github.com/exafmm/exafmm-t.git"