name: Run tests and style checks

on: push

jobs:
  get-branch:
    name: Get branch name
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get tag name
        id: vars
        run: |
            if [ ${GITHUB_REF#refs/*/} == "master" ]
            then
              echo ::set-output name=tag::latest
            else
              the_tag=${GITHUB_REF#refs/*/}
              echo ::set-output name=tag::${the_tag/\//_}
            fi
  style-checks:
    name: Run style checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
            sudo apt-get install -y python3-setuptools
            pip3 install black>=20.8
            pip3 install pydocstyle flake8
        name: Install Python style tools
      - run: |
            python3 -m flake8 pbj
            python3 -m flake8 test
        name: Run flake8 checks
      - run: |
            python3 -m black --line-length 88 --check pbj
        name: Run black checks in bempp
      - run: |
            python3 -m black --line-length 88 --check test
        name: Run black checks on tests
